name: ✨ Feature Request
description: Suggest a new feature or enhancement for XKit v3.0
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees:
  - rootkit-original
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make XKit better for everyone.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want to request...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of XKit would this feature belong to?
      options:
        - Core Functionality
        - MCP Integration
        - Plugin System
        - Event System
        - Git Operations
        - AI Integration
        - PowerShell Integration
        - CLI Commands
        - Documentation
        - Developer Experience
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (Critical for my workflow)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        I'm always frustrated when...
        Currently, I have to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution for this feature
      placeholder: |
        I would like to see...
        The feature should work like...
        For example...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        Alternatively, we could...
        Another approach might be...
        I currently work around this by...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this is a programmatic feature, how should the API look?
      placeholder: |
        ```python
        # Example API usage
        xkit.new_feature(param1="value", param2=True)
        ```
        
        ```powershell
        # Example CLI usage
        xkit new-command --option value
        ```
      render: markdown

  - type: checkboxes
    id: implementation-areas
    attributes:
      label: Implementation Areas
      description: Which parts of XKit would need to be modified? (Check all that apply)
      options:
        - label: Core Python backend
        - label: PowerShell wrapper functions
        - label: MCP server implementations
        - label: Plugin system
        - label: Event system
        - label: Configuration system
        - label: Documentation
        - label: Tests
        - label: CI/CD workflows

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - "No - Fully backward compatible"
        - "Minor - Small breaking changes acceptable"
        - "Major - Significant breaking changes required"
        - "Unknown - Needs investigation"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide concrete examples of how this feature would be used
      placeholder: |
        ## Example 1: Basic Usage
        ```
        xkit new-command arg1 arg2
        ```
        
        ## Example 2: Advanced Usage
        ```python
        from xkit import new_feature
        result = await new_feature.advanced_operation()
        ```
      render: markdown

  - type: checkboxes
    id: user-groups
    attributes:
      label: Target Users
      description: Who would benefit from this feature? (Check all that apply)
      options:
        - label: Developers using XKit daily
        - label: DevOps engineers
        - label: Git power users
        - label: AI/ML practitioners
        - label: Plugin developers
        - label: System administrators
        - label: New XKit users
        - label: PowerShell users
        - label: Python developers

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Would this feature require new dependencies or external services?
      placeholder: |
        - New Python packages: package-name>=1.0.0
        - External APIs: service-name API
        - System requirements: specific OS features

  - type: textarea
    id: testing-considerations
    attributes:
      label: Testing Considerations
      description: How should this feature be tested?
      placeholder: |
        Unit tests for...
        Integration tests with...
        Performance tests for...
        User acceptance criteria...

  - type: checkboxes
    id: contribution-interest
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I'd like to implement this feature myself
        - label: I can help with design and testing
        - label: I can provide feedback and testing
        - label: I'm interested but need guidance
        - label: I prefer to leave implementation to maintainers

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information about the feature
      placeholder: |
        Links to similar features in other tools:
        Mockups or diagrams:
        Related issues or discussions:
        Additional considerations:

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🎯 Feature Lifecycle
        
        After submission, this feature request will go through:
        
        1. **Triage**: Team review and categorization
        2. **Community Discussion**: Gather feedback from users
        3. **Design Review**: Technical design and architecture planning
        4. **Implementation**: Development and testing
        5. **Release**: Integration into XKit release
        
        ### 💡 Contributing
        
        Interested in helping implement this feature? Check our [Contributing Guide](../CONTRIBUTING.md) and [Plugin Development Guide](../docs/development/plugin-development.md).
        
        Thank you for making XKit better! 🚀